language: python

services:
  - docker

python:
  - "3.7"
  # PyPy versions
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
before_install:
  - docker build -t andresry/love-movies .
install:
  - pip install -r requirements.txt
  - 
# command to run tests
script: 
  - pytest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push andresry/love-movies